### ISSUE TITLE
response limited to 14000 rows

### ISSUE THREAD

**Issue by matreyes** [livebook-dev/req_bigquery#20]
Hi!

According to https://cloud.google.com/bigquery/docs/reference/rest/v2/jobs/query the requests are limited to a page. 
So when I try to process 500.000 rows, the count is correct, but the rows are only 14.000 
I would recommend to respond with a Stream.resource/3 to call the job again if we are requesting for more rows (pages), but I'm not sure if the Table protocol allows a Stream instead of List.

**Comment by josevalim** [comment]
I believe it supports any enumerable. Can you please try out a PR? Thank you!

**Comment by matreyes** [comment]
Sure!Matías Reyes Pace+56 9 9843 6786El 07-12-2022, a la(s) 18:13, José Valim ***@***.***> escribió:﻿
I believe it supports any enumerable. Can you please try out a PR? Thank you!

**Comment by josevalim** [comment]
I will go ahead and delete your previous comment since it had personal info (and I will delete this one later). :)

**Comment by matreyes** [comment]
(Ups.. bad idea responding trough email.)

Sure, challenge accepted!
