### ISSUE TITLE
Elixir native regular expressions support for parameter substitution

### ISSUE THREAD

**Issue by x123** [livebook-dev/req_bigquery#32]
Hi,

Thanks so much for the awesome library. It's very close to what I need for my use case, but I'm currently experiencing a problem when trying to do regular expression substitution using either the `{{name}}` style substitution or when using the `?` and `params` method.

What I'm trying to do:

```sql
SELECT
  submitted, username, url, email FROM `project_id.dataset.table`
WHERE 
  submitted BETWEEN DATETIME("2024-08-01") AND DATETIME("2024-09-05")
  AND
  regexp_contains(url, r'//(.*\.)?(domain1\.com|domain2\.com)$') # <-- I'd like to dynamically substitute the regex here
ORDER BY submitted DESC
```

I've tried many variations of trying to encode the regex both in the traditional native Elixir way (i.e., `~r'//(.*\.)?(domain1\.com|domain2\.com)$'`, dynamically attempting to substitute just a part inside the `r'regex{{inject}}'`, encoding it purely as a string, and so on. Unfortunately no matter what method I use I can't seem to get the query. I think it would be most natural to be able to do something along these lines:

```elixir
url_regex = ~r'//(.*\.)?(domain1\.com|domain2\.com)$'
query = """
SELECT
  submitted, username, url, email FROM `project_id.dataset.table`
WHERE 
  submitted BETWEEN DATETIME("2024-08-01") AND DATETIME("2024-09-05")
  AND
  regexp_contains(url, {{url_regex}}) # or the ? + params style
ORDER BY submitted DESC
"""
```

Admittedly, I'm not an Elixir expert. Any suggestions, maybe I'm missing something obvious?

**Comment by josevalim** [comment]
Could you use Elixir's regular interpolation instead?

```
url_regex = ~r'//(.*\.)?(domain1\.com|domain2\.com)$'

query = """
SELECT
  submitted, username, url, email FROM `project_id.dataset.table`
WHERE 
  submitted BETWEEN DATETIME("2024-08-01") AND DATETIME("2024-09-05")
  AND
  regexp_contains(url, r"#{Regex.source(url_regex)}") # or the ? + params style
ORDER BY submitted DESC
"""
```

or something of sorts. I assume you cannot pass a regular expression as parameter in BigQuery.

**Comment by x123** [comment]
> Could you use Elixir's regular interpolation instead?
> 
> ```
> url_regex = ~r'//(.*\.)?(domain1\.com|domain2\.com)$'
> 
> query = """
> SELECT
>   submitted, username, url, email FROM `project_id.dataset.table`
> WHERE 
>   submitted BETWEEN DATETIME("2024-08-01") AND DATETIME("2024-09-05")
>   AND
>   regexp_contains(url, r"#{Regex.source(url_regex)}") # or the ? + params style
> ORDER BY submitted DESC
> """
> ```
> 
> or something of sorts. I assume you cannot pass a regular expression as parameter in BigQuery.

Hi Jose, this worked perfectly. In Livebook I had to manually do something like:

```elixir
{:ok, _} = Goth.start_link(name: MyGoth, http_client: &Req.request/1)
req = Req.new() |> ReqBigQuery.attach(goth: MyGoth, project_id: "project-id")
result = Req.post!(req, bigquery: query).body
```

Unfortunately I could never get it to work with the SQL BigQuery Smart Cell in Livebook (either writing the whole query and just using `{{query}}` or trying to interpolate just the regex parts of it), so I just went down the manual route.

**Comment by josevalim** [comment]
Yes, the smart cell only works with actual parameters. For writing a custom query, you need to break out. Good job!
